# Generated by Django 3.0.4 on 2020-03-20 10:10

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Fornecedor', max_length=32)),
                ('email', models.EmailField(help_text='Contacto do Fornecedor (ie, email, telefone)', max_length=254)),
                ('lead', models.CharField(help_text='Identificação do lead', max_length=32)),
                ('origin', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição do produto', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(blank=True, help_text='Marca do Produto', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo do Produto', max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default=1, help_text='Nome do Produto', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='availability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='ce_certified',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fda_certified',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='proposal',
            name='min_order_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Termos de pagamento', max_length=128),
        ),
        migrations.AddField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producttype',
            name='designation',
            field=models.CharField(help_text='Designação do Produto', max_length=128),
        ),
        migrations.CreateModel(
            name='ProposalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_file', models.FileField(upload_to='')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.Supplier')),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='supplier',
            field=models.ForeignKey(help_text='Nome do Fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Supplier'),
        ),
    ]
