# Generated by Django 3.0.4 on 2020-03-20 11:47

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20200320_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(help_text='Tipo de Documento', max_length=64)),
                ('description', models.CharField(help_text='Descrição do Documento', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposaldocuments',
            name='technical_file',
        ),
        migrations.AddField(
            model_name='donation',
            name='availability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposaldocuments',
            name='file',
            field=models.FileField(default=1, upload_to='./uploads/files/<django.db.models.fields.related.ForeignKey>/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='./uploads/images/<property object at 0x7f76a4156548>/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Contacto do Fornecedor (ie, email, telefone)', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead',
            field=models.CharField(blank=True, help_text='Identificação do lead', max_length=32),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='proposaldocuments',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='management.DocumentType'),
            preserve_default=False,
        ),
    ]
