# Generated by Django 3.0.4 on 2020-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20200320_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='./uploads/images/<property object at 0x7f4cd3492548>/', width_field='width'),
        ),
    ]
