# Generated by Django 3.0.4 on 2020-03-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200320_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, help_text='Nome do Fornecedor', on_delete=django.db.models.deletion.DO_NOTHING, to='management.Supplier'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='./uploads/images/<property object at 0x7f1a79aab548>/', width_field='width'),
        ),
    ]
