# Generated by Django 3.0.4 on 2020-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20200320_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(height_field='height', upload_to='./uploads/images/<property object at 0x7fb7f6a13548>/', width_field='width'),
        ),
    ]
