# Generated by Django 3.0.4 on 2020-03-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200320_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(upload_to='./uploads/images/'),
        ),
        migrations.AlterField(
            model_name='proposaldocuments',
            name='file',
            field=models.FileField(upload_to='./uploads/files/'),
        ),
    ]
