# Generated by Django 3.0.4 on 2020-03-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20200321_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
