# Generated by Django 3.0.4 on 2020-03-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='make',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='proposal',
            name='comments',
            field=models.TextField(blank=True, help_text='Notas/ Comentários', max_length=1024),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do Fornecedor', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição do produto', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo do Produto', max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Nome do Produto', max_length=64),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='availability',
            field=models.IntegerField(help_text='Inserir valor total sem abreviatura'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='min_order_quantity',
            field=models.IntegerField(help_text='Inserir valor total sem abreviatura'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do fornecedor', max_length=254),
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Tipo de Produto', max_length=32)),
                ('designation', models.CharField(help_text='Designação do Produto', max_length=128)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_subtype',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductSubType'),
        ),
    ]
