# Generated by Django 3.0.4 on 2020-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200321_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subtype',
        ),
        migrations.DeleteModel(
            name='ProductSubType',
        ),
    ]
