# Generated by Django 3.0.4 on 2020-03-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20200321_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Tipo de Produto', max_length=32)),
                ('designation', models.CharField(help_text='Designação do Produto', max_length=128)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductType')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_subtype',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductSubType'),
        ),
    ]
