# Generated by Django 3.0.4 on 2020-03-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20200321_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(blank=True, choices=[('D', 'Doação'), ('C', 'Comercial')], help_text='Tipo de Proposta', max_length=24),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='min_order_quantity',
            field=models.IntegerField(blank=True, help_text='Inserir valor total sem abreviatura'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
