# Generated by Django 3.0.4 on 2020-03-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20200321_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subtype',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductType'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(blank=True, default=None, help_text='Tipo de Produto', max_length=32),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(blank=True, choices=[('E', 'Equipamento Protecao Individual'), ('V', 'Ventilador'), ('T', 'Kit Teste')], default=None, help_text='Tipo de Produto', max_length=32),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Product'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(blank=True, choices=[('D', 'Doação'), ('C', 'Comercial')], default=None, help_text='Tipo de Proposta', max_length=24),
        ),
        migrations.DeleteModel(
            name='ProductSubType',
        ),
    ]
