# Generated by Django 3.0.4 on 2020-03-21 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20200321_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposaldocuments',
            options={'verbose_name': 'Proposal Document', 'verbose_name_plural': 'Proposal Documents'},
        ),
        migrations.AlterField(
            model_name='producttype',
            name='designation',
            field=models.CharField(blank=True, help_text='Designação do Produto', max_length=128),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='proposaldocuments',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='proposaldocuments',
            name='file_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.DocumentType'),
        ),
        migrations.AlterField(
            model_name='proposaldocuments',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Proposal'),
        ),
    ]
