# Generated by Django 3.0.4 on 2020-03-21 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20200321_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.ProductType'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Product'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, help_text='Nome do Fornecedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.Supplier'),
        ),
    ]
