# Generated by Django 3.0.4 on 2020-03-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20200321_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.ProductType'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Product'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, help_text='Nome do Fornecedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Supplier'),
        ),
        migrations.AlterField(
            model_name='proposaldocuments',
            name='file_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.DocumentType'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('P', 'Prospective'), ('O', 'Ordered'), ('A', 'Arrived'), ('C', 'Cancelled')], max_length=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Product')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.Proposal')),
            ],
        ),
    ]
