# Generated by Django 3.0.4 on 2020-03-22 00:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_auto_20200321_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, help_text='Descrição do produto', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, help_text='Modelo do Produto', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='designation',
            field=models.CharField(blank=True, help_text='Designação do Produto', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(blank=True, default=None, help_text='Tipo de Produto', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='type',
            field=models.CharField(blank=True, choices=[('E', 'Equipamento Protecao Individual'), ('V', 'Ventilador'), ('T', 'Kit Teste')], default=None, help_text='Tipo de Produto', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='comments',
            field=models.TextField(blank=True, help_text='Notas/ Comentários', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='min_order_quantity',
            field=models.IntegerField(blank=True, help_text='Inserir valor total sem abreviatura', null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Termos de pagamento', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(blank=True, choices=[('D', 'Doação'), ('C', 'Comercial')], default=None, help_text='Tipo de Proposta', max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email do fornecedor', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='lead',
            field=models.CharField(blank=True, help_text='Identificação do lead', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone do Fornecedor', max_length=32, null=True),
        ),
    ]
