# Generated by Django 3.0.4 on 2020-03-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20200322_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='management.Product'),
        ),
    ]
